# DISCLAIMER
# This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
# No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
# applicable laws, including copyright laws.
# THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
# OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
# LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
# INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
# ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability
# of this software. By using this software, you agree to the additional terms and conditions found by accessing the
# following link:
# http://www.renesas.com/disclaimer
#
# Generated from SVD 1.2, with svd2pac 0.6.0 on Thu, 24 Jul 2025 04:45:52 +0000

[package]
name = "da1470x-pac"
version = "0.2.0"
edition = "2024"
description = "Peripheral Access Crate (PAC) for DA1470X."
authors = ["Tri Nguyen <trongtribk06@gmail.com>"]
keywords = ["da1470x", "da", "arm", "cortex-m", "renesas"]
repository = "https://github.com/nguyentri/da-pac"
documentation = "https://docs.rs/crate/da1470x-pac/latest"
categories = ["embedded", "hardware-support", "no-std"]
include = ["src/*", "Cargo.toml", "README.md", "build.rs", "device.x"]
readme = "README.md"
license = "MIT OR Apache-2.0"

[lib]
test = false
bench = false

[dependencies]
phf = { version = "0.12.1", features = ["macros"], optional = true }
cortex-m-rt = { version = "0.7", optional = true }
cortex-m = "0.7.6"

[features]
aes_hash = []
anamisc_bif = []
cache = []
charger = []
chg_det = []
crg_aud = []
crg_ctrl = []
crg_gpu = []
crg_snc = []
crg_sys = []
crg_top = []
crg_vsys = []
crg_xtal = []
dcache = []
dcdc = []
dcdc_boost = []
dma = []
dsi2 = []
dsidphy_reg = []
emmc = []
gpadc = []
gpio = []
gpreg = []
gpu_core = []
gpu_reg = []
i2c = []
i2c2 = []
i2c3 = []
i3c = []
lcdc = []
memctrl = []
oqspif = []

all = ["aes_hash" , "anamisc_bif" , "cache" , "charger" , "chg_det" , "crg_aud" , "crg_ctrl" , "crg_gpu" , "crg_snc" , "crg_sys" , "crg_top" , "crg_vsys" , "crg_xtal" , "dcache" , "dcdc" , "dcdc_boost" , "dma" , "dsi2" , "dsidphy_reg" , "emmc" , "gpadc" , "gpio" , "gpreg" , "gpu_core" , "gpu_reg" , "i2c" , "i2c2" , "i2c3" , "i3c" , "lcdc" , "memctrl" , "oqspif"]

tracing = ["dep:phf"]

tracing_dummy = []

rt = ["cortex-m-rt/device"]

[package.metadata.docs.rs]
features = ["all", "rt"]
